from __future__ import annotations

import sys
from pathlib import Path
from typing import Any, Dict, Optional


BASE_DIR = Path(__file__).resolve().parents[2]
CLADD_DIR = BASE_DIR / "CLADD"

if str(CLADD_DIR) not in sys.path:
    sys.path.insert(0, str(CLADD_DIR))

from run_molt5_caption import generate_molt5_caption  # type: ignore  # noqa: E402


def _build_error_payload(drug_name: str, smiles: str, exc: Exception) -> Dict[str, Any]:
    return {
        "drug_name": drug_name,
        "molt5_description": "",
        "message": str(exc),
    }


def _normalize_query_inputs(
    drug_name: Optional[str] = None,
    smiles: Optional[str] = None,
) -> Dict[str, str]:
    normalized_drug_name = str(drug_name or "").strip()
    normalized_smiles = str(smiles or "").strip()

    if normalized_drug_name and normalized_smiles:
        raise ValueError("Please provide either drug_name or smiles, not both.")
    if not normalized_drug_name and not normalized_smiles:
        raise ValueError("Please provide either drug_name or smiles.")

    return {
        "drug_name": normalized_drug_name,
        "smiles": normalized_smiles,
    }


def get_cladd_molt5_description(
    drug_name: Optional[str] = None,
    smiles: Optional[str] = None,
) -> Dict[str, Any]:
    """
    Given either a drug name or a SMILES string, return the MolT5 molecular
    description generated by the local CLADD captioning pipeline together with
    the resolved query SMILES.
    """
    try:
        query = _normalize_query_inputs(drug_name=drug_name, smiles=smiles)
    except Exception as exc:
        return _build_error_payload(str(drug_name or "").strip(), str(smiles or "").strip(), exc)

    try:
        result = generate_molt5_caption(
            drug_name=query["drug_name"] or None,
            smiles=query["smiles"] or None,
            device=0,
            num_beams=5,
            max_length=512,
        )
    except Exception as exc:
        return _build_error_payload(query["drug_name"], query["smiles"], exc)

    return {
        "drug_name": query["drug_name"],
        "molt5_description": result.get("molt5_description", ""),
        "message": (
            "Matched successfully."
            if result.get("molt5_description")
            else "Empty MolT5 description."
        ),
    }


get_cladd_molt5_description_doc = {
    "type": "function",
    "name": "get_cladd_molt5_description",
    "description": (
        "Given either a drug name or a SMILES string, use the local CLADD MolT5 captioning pipeline "
        "to resolve the query and return the generated molecular description. Provide exactly one of "
        "`drug_name` or `smiles`. The result includes drug_name, molt5_description, and message."
    ),
    "parameters": {
        "type": "object",
        "properties": {
            "drug_name": {
                "type": "string",
                "description": "Drug name to resolve in CLADD/PrimeKG. Use this or smiles.",
            },
            "smiles": {
                "type": "string",
                "description": "SMILES string to describe directly with MolT5. Use this or drug_name.",
            },
        },
        "required": [],
    },
}
